#=================================================================#
#=                    SYNTAX HIGHLIGHT TPP                       =#
#=================================================================#
#= 1: Para instalar copie os dois arquivos para:                 =#
#= ~/.config/sublime-text-3/Packages/User/                       =#
#= esta operação é feita apenas utilizando o comando make        =#
#=================================================================#
#= 2: Para ativar no Sublime, vá em:                             =#
#= View->Syntax->Open all with current extension as ...->TPP     =#
#=================================================================#
#= 3: Para alterar o esquema de cor no Sublime, vá em:           =#
#= Preferences->Color Scheme...=> tpp (User)                     =#
#=================================================================#
#=                          PRONTO.                              =#
#=             AÇO, FOGO E BALAÇO; SELVA PURA                    =#
#=================================================================#

all: copia instrucoes

copia:
	cp tpp.sublime-syntax ~/.config/sublime-text-3/Packages/User/
	cp tpp.sublime-color-scheme ~/.config/sublime-text-3/Packages/User/

instrucoes:
	head -n 16 makefile